apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
data:
  use-proxy-protocol: "true"
  enable-sticky-sessions: "true"
  # enable-vts-status: "true"
  server-name-hash-bucket-size: "128"
  proxy-buffers: "8 16k"
  proxy-buffer-size: "16k"
