apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: "{{ template "fullname" . }}-fluentd"
data:
  elasticsearch_host: "{{ .Values.Elasticsearch.Host }}"
  elasticsearch_port: "{{ .Values.Elasticsearch.Port }}"
  fluent.conf: |
    <source>
      type tail
      format none
      path /var/log/rstudio-server/rserver-http-access.log
      pos_file /var/log/rstudio-server/rserver-http-access.pos
      read_from_head true
      tag rstudio-access
    </source>

    <source>
      type tail
      format none
      path /var/log/rstudio-server/rserver-http-error.log
      pos_file /var/log/rstudio-server/rserver-http-error.pos
      read_from_head true
      tag rstudio-error
    </source>

    <match **>
       type elasticsearch
       log_level info
       include_tag_key true
       host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
       port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
       logstash_format true
       buffer_chunk_limit 2M
       buffer_queue_limit 32
       flush_interval 5s
       max_retry_wait 30
       disable_retry_limit
       num_threads 8
    </match>
