Username: ""
ToolsDomain: "tools.EXAMPLE.COM"
CookieSecret: ""
app:
  name: ""
  baseHost: ""
  replicaCount: 3
  port: 80
  repo: ""
AuthProxy:
  AuthenticationRequired: "true"
  IPRanges: ""
  Image:
    Repository: quay.io/mojanalytics/auth-proxy
    Tag: "v0.2.0"
    PullPolicy: "IfNotPresent"
AWS:
  AccessKeyId: ""
  SecretAccessKey: ""
  DefaultRegion: "eu-west-1"
OAuth:
  ClientSecret: ""
  ClientId: ""
  Domain: "AUTH0_USER.eu.auth0.com"
shinyApp:
  port: 3838
  docker:
    repository: ""
    tag: latest
    pullPolicy: Always
Fluentd:
  Image:
    Repository: quay.io/fluent/fluentd-kubernetes-daemonset
    Tag: latest
    PullPolicy: "IfNotPresent"
Elasticsearch:
  Host: ""
  Port: "9200"
